### ISSUE TITLE
mocking backend output

### ISSUE THREAD

**Issue by AltiMario** [mlabs-haskell/TuxedoDapp#37]
We are investigating if it is possible to compile the Rust code of the CLI Wallet in WASM, in order to inject it in javascript.
If everything goes well, you don't need to port the Rust code implemented in Javascript and there is no need to call to a backend server because everything will be local.

This ticket is about creating mocking functions that return the perfect output for the frontend, to simulate the needed output for the interface. When the WASM is ready the mock part can be substituted.

**Comment by NadigerAmit** [comment]
Current situation of the investigation: Although I am able to call the normal rust code which is compiled to wasm using wasm-bindgen from js code, I am still not successful in porting the simple code from wallet-cli due to compilation issues:

Details of the issue : https://github.com/Off-Narrative-Labs/Tuxedo/issues/189
