### ISSUE TITLE
BlockChain - Piece: Adding kittie details

### ISSUE THREAD

**Issue by AltiMario** [mlabs-haskell/TuxedoDapp#5]
Adding more details of kitties such as Gender, Tradable status, Price, and Name.
This was in the proposal.

**Comment by NadigerAmit** [comment]
This is done 

Blockcside implementation 

Name of Kitty : https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wardrobe/kitties/src/lib.rs#L212

Price : https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wardrobe/tradable_kitties/src/lib.rs#L60

Gender no need to add , since parent field is samin KittyData is same as Gender.
Tradable status is also not needed , as Price field is Option i.e it can take any of the 2 values i.e Some() Or None 

If it None , then the kitty is not for sale and if it is Some() then kitty is for sale.

Please see this issue for more details on how to update name and price : https://github.com/mlabs-haskell/TuxedoDapp/issues/9

**Comment by NadigerAmit** [comment]
Since blockchain-side implementation is done I moving to Done as it is already submitted in the https://github.com/mlabs-haskell/Tuxedo
