### ISSUE TITLE
don't buy what is no longer for sale

### ISSUE THREAD

**Issue by AltiMario** [mlabs-haskell/TuxedoDapp#58]
_There is one issue in the frontend as it shows Kitties that already have been bought still as "for sale" so the UI support you in creating a TX to buy this even though it has just been bought and is actually no longer for sale. These transactions fail and it doesn't change the owner again._

**Comment by AltiMario** [comment]
It bug was discovered by the reviewer https://github.com/w3f/Grant-Milestone-Delivery/pull/1170#issuecomment-2358866217

**Comment by AltiMario** [comment]
I just tested again and the anomaly is confirmed. 
I would consider it a flaw in business logic.

**Comment by nrutledge** [comment]
@AltiMario I tested as well and noticed that the kitty doesn't just remain on sale in the fronted, the backend continues to have it marked for sale after the transfer of ownership. However, it can be purchased as expected when switching accounts (after refreshing the page).

A quick fix would be to optimistically update the kitty on the frontend so that the owner updates immediately after the purchase transaction is submitted. This would prevent someone from seeing the option to buy after they've already purchased. However, this approach has a couple limitations:
1. If the user refreshes the page (as they might be inclined to do) before the transaction is complete and backend updated, stale data might be fetched, allowing the user to see the option to buy again.
2. If the transaction fails for any reason, the frontend will still show that the kitty transferred owners when it didn't in reality (until the page is refreshed).

A more robust solution would be to update the backend logic so that the kitty is marked as not for sale after a purchase, and to also improve communication between backend and frontend, such that things remain in a pending status while transactions are being confirmed, update afterwards, etc. But I assume that is out of scope for now.

Would you like me to proceed with the simple optimistic update on the frontend?

**Comment by AltiMario** [comment]
hi @nrutledge  I believe fixing the frontend first is the best approach. Well done on sharing the concerns 1 and 2. 
Should this frontend fix not meet the reviewer expectations, we can then address the backend without affecting the frontend changes. 
Is it correct?

**Comment by nrutledge** [comment]
@AltiMario that's correct, the backend changes wouldn't conflict directly with the frontend changes. However, for now I would just optimistically update the owner and not the "for sale" status (to be consistent with current backend behavior). After fixing on the backend, there would just be a slight discrepancy with the status, but it would go away on refresh.

I'll create a PR with the frontend change today.
